version: "3.9"
services:
  app:
    build: .
    environment:
      - NODE_ENV=${NODE_ENV:-develop}
      - DEFAULT_DOCKER_CMD=${DEFAULT_DOCKER_CMD}
    volumes:
      - ./:/home/app
    ports:
      - "3000:3000"
